# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeployCil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('name', models.CharField(max_length=64, verbose_name='\u90e8\u7f72\u540d\u79f0')),
                ('command', models.CharField(max_length=512, verbose_name='\u90e8\u7f72\u547d\u4ee4')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
                ('memo', models.TextField(blank=True, max_length=1024, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'gadmin_deploy',
                'verbose_name': '\u90e8\u7f72\u547d\u4ee4\u8868',
                'verbose_name_plural': '\u90e8\u7f72\u547d\u4ee4\u5217\u8868',
            },
        ),
    ]
