# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploycil',
            name='command',
            field=models.TextField(max_length=512, verbose_name='\u90e8\u7f72\u547d\u4ee4'),
        ),
    ]
