# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GovProAttrExclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('main_word', models.CharField(db_index=True, help_text='\u5c5e\u6027\u5b57\u6bb5\u540d\u79f0', max_length=64, verbose_name='\u4e3b\u8bcd')),
                ('attribute_field', models.CharField(max_length=32, verbose_name='\u5c5e\u6027\u5b57\u6bb5')),
                ('exclude_word', models.CharField(max_length=64, verbose_name='\u6392\u65a5\u8bcd')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'db_table': 'wordutil_govpro_attr_exclude_word',
                'verbose_name': '\u5c5e\u6027\u6392\u65a5\u8bcd\u8868',
                'verbose_name_plural': '\u5c5e\u6027\u6392\u65a5\u8bcd\u5217\u8868',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GovProAttrSyn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('main_word', models.CharField(db_index=True, help_text='\u5c5e\u6027\u5b57\u6bb5\u540d\u79f0', max_length=64, verbose_name='\u4e3b\u8bcd')),
                ('attribute_field', models.CharField(max_length=32, verbose_name='\u5c5e\u6027\u5b57\u6bb5')),
                ('synonym_word', models.CharField(max_length=64, verbose_name='\u8fd1\u4e49\u8bcd')),
                ('valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6709\u6548')),
            ],
            options={
                'db_table': 'wordutil_govpro_attrsyn',
                'verbose_name': '\u5c5e\u6027\u8fd1\u4e49\u8bcd\u8868',
                'verbose_name_plural': '\u5c5e\u6027\u8fd1\u4e49\u8bcd\u5217\u8868',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='govproattrsyn',
            unique_together=set([('main_word', 'synonym_word')]),
        ),
        migrations.AlterUniqueTogether(
            name='govproattrexclude',
            unique_together=set([('main_word', 'exclude_word')]),
        ),
    ]
