# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='govhostinfo',
            options={'verbose_name': '\u7ad9\u70b9\u4fe1\u606f\u8868', 'verbose_name_plural': '\u7ad9\u70b9\u4fe1\u606f\u5217\u8868'},
        ),
    ]
