# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import govbuy.models.govhost


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0002_auto_20161129_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('host_id', models.IntegerField(db_index=True, verbose_name='\u4e3b\u7ad9id')),
                ('host_url', models.CharField(max_length=128, verbose_name='\u7ad9\u70b9\u5730\u5740')),
                ('project_page_url', models.CharField(max_length=512, verbose_name='\u9879\u76ee\u9875\u9762url')),
                ('is_crawled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6293\u53d6\u5b8c\u6210')),
                ('crawl_time', models.DateTimeField(blank=True, null=True, verbose_name='\u6293\u53d6\u65f6\u95f4')),
                ('html_source_code', models.TextField(blank=True, max_length=102400, null=True, verbose_name='\u9875\u9762\u539f\u59cb\u5185\u5bb9')),
                ('accessory', models.FileField(blank=True, upload_to=govbuy.models.govhost.accessory_path, verbose_name='\u9644\u4ef6')),
            ],
            options={
                'db_table': 'gov_project_crawl_page_info',
                'verbose_name': '\u7ad9\u70b9\u6293\u53d6\u4fe1\u606f\u8868',
                'verbose_name_plural': '\u7ad9\u70b9\u6293\u53d6\u4fe1\u606f\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='govhostinfo',
            name='host_url',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u7ad9\u70b9\u5730\u5740'),
        ),
        migrations.AlterUniqueTogether(
            name='crawlpage',
            unique_together=set([('host_id', 'project_page_url')]),
        ),
    ]
