# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0004_crawlpage_logogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='govhostinfo',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u53ef\u6253\u5f00'),
        ),
    ]
