# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0005_govhostinfo_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlpage',
            name='extract_type',
            field=models.CharField(choices=[('manual', '\u4eba\u5de5\u63d0\u53d6'), ('machine', '\u673a\u5668\u63d0\u53d6'), ('correct', '\u4eba\u5de5\u77eb\u6b63')], db_index=True, default='machine', max_length=8, verbose_name='\u63d0\u53d6\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='govproject',
            name='let_contract_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u62db\u6807\u65f6\u95f4'),
        ),
    ]
