# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0007_auto_20161214_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govproject',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('issue', '\u53d1\u5e03\u65b9'), ('bid', '\u62db\u6807\u65b9'), ('tender', '\u6295\u6807\u65b9'), ('agency', '\u4ee3\u7406\u65b9')], max_length=8, verbose_name='\u7c7b\u578b'),
        ),
    ]
