# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0008_auto_20161220_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govproject',
            name='bid_no',
        ),
        migrations.AddField(
            model_name='govproject',
            name='bid_type',
            field=models.CharField(blank=True, choices=[('inquiry', '\u8be2\u4ef7\u65b9\u5f0f')], max_length=16, null=True, verbose_name='\u62db\u6807\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='govproject',
            name='project_progress',
            field=models.CharField(choices=[('study_out', '\u62df\u5b9a'), ('bid', '\u62db\u6807\u4e2d'), ('win', '\u4e2d\u6807'), ('abandon', '\u5e9f\u6807'), ('abortion', '\u6d41\u6807'), ('working', '\u5f00\u5de5'), ('end', '\u7ed3\u675f'), ('die', '\u4e2d\u6b62')], max_length=16, verbose_name='\u9879\u76ee\u8fdb\u5ea6'),
        ),
    ]
