# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0009_auto_20170319_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='govproject',
            name='bid_no',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u62db\u6807\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='govproject',
            name='bid_type',
            field=models.CharField(blank=True, choices=[('inquiry', '\u8be2\u4ef7\u91c7\u8d2d')], max_length=16, null=True, verbose_name='\u62db\u6807\u65b9\u5f0f'),
        ),
    ]
