# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-19 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0010_auto_20170319_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='govproject',
            name='purchase_org',
            field=models.CharField(max_length=128, null=True, verbose_name='\u62db\u6807\u91c7\u8d2d\u673a\u6784'),
        ),
        migrations.AddField(
            model_name='govproject',
            name='purchase_org_id',
            field=models.IntegerField(null=True, verbose_name='\u62db\u6807\u91c7\u8d2d\u673a\u6784id'),
        ),
    ]
