# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govbuy', '0011_auto_20170319_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govproject',
            name='qualification_requirement',
            field=models.CharField(blank=True, max_length=10240, null=True, verbose_name='\u8d44\u8d28\u8981\u6c42'),
        ),
    ]
